// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "KDH_Hot"
#define SECRET_PASS "1q2w3e4r"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a1q2edrb47pqsq-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICijCCAXKgAwIBAgIUUNi0W4ae90pawxzXDRfUtZLRPiMwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTIwNjA4NDgz
OVoXDTQ5MTIzMTIzNTk1OVowGjEYMBYGA1UEAxMPV2F0ZXJ3YXlQcm9qZWN0MFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZA9rZaoEmbroIp1BV3rvE3ivGRCl+MUU
t9cuFdq1eM050c6VRRmVHYHk+xpYMrPGgHq9EU8h+pGwNRWTGx2GLqNgMF4wHwYD
VR0jBBgwFoAUtVNLmyPmT9YOYUpffofipunBqY8wHQYDVR0OBBYEFDtOmXuOajmF
6Ux8fYmSRXiCeiANMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMA0GCSqG
SIb3DQEBCwUAA4IBAQC4jECdo6kHDXiClEP+lnEhNyEvW9Xv2NLMTsHaL8WGB6Zv
RKcMjAwEmbADG/JshAEOnrN3lhKid3QhdLw663VQRD1V0xv1f2tr04SxZoRcbG69
vOkGFxU+7LuaEMBkXaMkwYsr6Ulj5xR0FpJMIGeV4zhzmE0yTdqsXr5++uDBMJf9
EGmFoLt3c1FB59vde2HrBmzQTawo9ijUsgiwSSydlLBFLSiBkzCPmu+i4W8okbt7
QTqA0X/R19WZXkZ5Bc1zNwBH/lWNGUBKdohJkBbD94B6Mb+zLNrDhUBx+iXbedic
FymTNgONkjKm/regblU+wBwNGJGqVWQvSroP8h3U
  -----END CERTIFICATE-----
)";
