// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "KDH_Hot"
#define SECRET_PASS "1q2w3e4r"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a1q2edrb47pqsq-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICijCCAXKgAwIBAgIUahWd5uY2DuXl18+0fBUwMqxJE1YwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTEzMDEwNDY0
OFoXDTQ5MTIzMTIzNTk1OVowGjEYMBYGA1UEAxMPV2F0ZXJ3YXlQcm9qZWN0MFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZA9rZaoEmbroIp1BV3rvE3ivGRCl+MUU
t9cuFdq1eM050c6VRRmVHYHk+xpYMrPGgHq9EU8h+pGwNRWTGx2GLqNgMF4wHwYD
VR0jBBgwFoAUbqzJaI2VC4qdI14tbm5XN3/9cG8wHQYDVR0OBBYEFDtOmXuOajmF
6Ux8fYmSRXiCeiANMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMA0GCSqG
SIb3DQEBCwUAA4IBAQBZjjWgOrENAS64GuP1wGrYlWJklqFmg9qIDDQT/vqyEbhC
SFyS5vBvGAVxdFzmSFyw1+zRsTyd/+XOlj/PjrVn5YfiE63pa+PQNw6EwcPBMrjB
uPP08gR7JLHmQ54wDUr3lMwUCrWvUx/ybZEEzQl6LDG5NUS2VKmiPLqjS8fQM8b7
ZI6FKrMbsORXA1joxcb7YFbuN+ONGa4RsKsEhM+y50PaA1MxvSv49+JdNycDBzCI
9AoZ60nWZYXraa7zvgfPBi0dw+qu0CcWSeOlkWSbD01h8t/Sxxd8Rg+BQvXauaz2
ud/MwI/wSNK/gQOUNnW7z8AGKmlB9Ck/CAk+f7Nr
  -----END CERTIFICATE-----
)";
